import { Hero } from "@/components/Hero";
import "./globals.css";
import { Header } from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-307.5 flex flex-col mx-auto">
        <Header />
        <Hero />
        {children}
      </body>
    </html>
  );
}
